services:
  - type: web
    name: gold-server
    env: node
    plan: free
    buildCommand: npm install && npx playwright install chromium
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_VERSION
        value: 20.11.0
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
